### PR TITLE
bower: Updated bootstrap dependency to v3.0.2

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by NKjoep** [comment]
I was trying to do the same... however please tell me, isn't enough to change the bower dependency?

**Comment by Turbo87** [comment]
sure, but then the generated files in the `dist` folder would be outdated

**Comment by eins78** [comment]
That is correct, but don't be confused: It is only important for pull requests to this repo.
In your won repo, it would update anyhow when you make changes (but the git history wouldn't be as clean).

Anyhow, have you also reviewed the changes in bootstrap, @Turbo87?
Can we just merge or are there breaking changes?

**Comment by Turbo87** [comment]
as far as I can remember I tested the changes back when I did those commits, but feel free to verify them. by now bootstrap has already upgraded to v3.1.1 so it might be worth it to integrate that version as well.

**Comment by NKjoep** [comment]
I think it always usefult to integrate previous version... It would be very cool to have a tagged version of themestrap with different bootstrap versions :)

**Comment by trumbitta** [comment]
Yep, once this pull request is verified and merged I think we could certainly tag for v3.0.2.  
Then we could do the same for v3.1.1

**Comment by Turbo87** [comment]
looks like this project is essentially dead, so I'm closing this PR.

**Pull request closed without merging**
